.\" This file is comment.
.TH odin 1 "July 2011" "Reportbase Project"
.SH NAME
odin \- update symbol history
.SH SYNOPSIS
\fBodin\fP [binary-path] [html-path] [list]
.br
.SH DESCRIPTION
\fBodin\fP update symbol history
.PP
.SH OPTIONS
The following options are available:
.TP
\fB--help\fP
Show usage.
.TP
\fB--version\fP
Show version number.
.SH EXAMPLES
.nf
$ odin /usr/local/var/series.dat /usr/local/var/symbols.dat "select * from symbols"
.fi
.SH AUTHORS
Tom Brinkman
